name: Java CI

on:
  push:
    branches:
    - main
    paths:
    - 'src/**'
    - 'pom.xml'
  pull_request:
    branches:
    - main
    paths:
    - 'src/**'
    - 'pom.xml'

jobs:
  build:

    name: Maven build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@main
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
